-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 14:20:40 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_loja_esportiva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_loja_esportiva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_loja_esportiva` DEFAULT CHARACTER SET utf8 ;
USE `bd_loja_esportiva` ;

-- -----------------------------------------------------
-- Table `bd_loja_esportiva`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_loja_esportiva`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_loja_esportiva`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_loja_esportiva`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `data_pedido` DATE NOT NULL,
  `status_pedido` CHAR(1) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_pessoa_idx` (`idpessoa` ASC) ,
  CONSTRAINT `fk_pedido_pessoa`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `bd_loja_esportiva`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_loja_esportiva`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_loja_esportiva`.`setor` (
  `idsetor` INT NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsetor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_loja_esportiva`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_loja_esportiva`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `idsetor` INT NOT NULL,
  `produto` VARCHAR(20) NOT NULL,
  `descricao_produto` TEXT(100) NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `unidade` CHAR(20) NOT NULL,
  `estoque` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_setor1_idx` (`idsetor` ASC) ,
  CONSTRAINT `fk_produto_setor1`
    FOREIGN KEY (`idsetor`)
    REFERENCES `bd_loja_esportiva`.`setor` (`idsetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_loja_esportiva`.`pedidoproduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_loja_esportiva`.`pedidoproduto` (
  `idpedido` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idpedido`, `idproduto`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`idproduto` ASC) ,
  INDEX `fk_pedido_has_produto_pedido1_idx` (`idpedido` ASC) ,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`idpedido`)
    REFERENCES `bd_loja_esportiva`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`idproduto`)
    REFERENCES `bd_loja_esportiva`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
